name: Generate a build ans push

on:
  push:
    branches:
      -main
      
jobs:
  build:
    runs-on: ubuntu-lastest
    name: build
    steps:
      - run: npm install
      
      - run: npm run build
      
      - uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: dist
